// This file is generated by Firebase Extensions.
//
// Please do not modify it directly.

'use server';

/**
 * @fileOverview Classifies a product name into the most appropriate HS Code and description using the Gemini API.
 *
 * - classifyProduct - A function that handles the product classification process.
 * - ClassifyProductInput - The input type for the classifyProduct function.
 * - ClassifyProductOutput - The return type for the classifyProduct function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ClassifyProductInputSchema = z.object({
  productName: z.string().describe('The name of the product to classify.'),
});
export type ClassifyProductInput = z.infer<typeof ClassifyProductInputSchema>;

const ClassifyProductOutputSchema = z.object({
  analysisText: z.string().describe('Analysis of the product classification.'),
  hsCode: z.string().describe('The 6-digit HS Code for the product.'),
  categoryDescription: z.string().describe('The description of the HS Code category.'),
});
export type ClassifyProductOutput = z.infer<typeof ClassifyProductOutputSchema>;

export async function classifyProduct(input: ClassifyProductInput): Promise<ClassifyProductOutput> {
  return classifyProductFlow(input);
}

const prompt = ai.definePrompt({
  name: 'classifyProductPrompt',
  input: {schema: ClassifyProductInputSchema},
  output: {schema: ClassifyProductOutputSchema},
  prompt: `You are an expert in classifying products into the Harmonized System (HS) Code. Given a product name, you will classify it into the most appropriate 6-digit HS Code and provide a description of the category.

Product Name: {{{productName}}}

Here is a list of possible HS Codes and descriptions:
010200 - Binatang hidup jenis lembu
847130 - Mesin pemproses data otomatis, portabel
902511 - Termometer, tidak dikombinasikan dengan peralatan lain
630790 - Kain lap

Based on the product name and the list above, provide the analysis, HS Code, and category description.

Make sure that the HS Code contains only numbers, and is 6 digits long.

Output the HS Code and the category description exactly as shown in the list above.

Analysis Text:
HS Code:
Category Description:`, // Add sample prompt here
});

const classifyProductFlow = ai.defineFlow(
  {
    name: 'classifyProductFlow',
    inputSchema: ClassifyProductInputSchema,
    outputSchema: ClassifyProductOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
